/* Generated by gbrecomp */
#ifndef pokeblue_H
#define pokeblue_H

#include "gbrt.h"

const GBConfig* pokeblue_default_config(void);
void pokeblue_run(GBContext* ctx);
void pokeblue_init(GBContext* ctx);
int pokeblue_main(int argc, char* argv[]);

#endif
